# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170904_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
    ]
